name = "Taco Mods"
author = "SLLCoding"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec0198221bcb5e7a48859f631480a3a10200252fcebe8a3daaf739809e602377"

[versions]
fabric = "0.14.9"
minecraft = "1.18.2"
